version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: matchup_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: matchup_db
      POSTGRES_USER: matchup_user
      POSTGRES_PASSWORD: matchup_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - matchup_network

volumes:
  postgres_data:

networks:
  matchup_network:
    driver: bridge